var GAME_LEVELS = [
	[
		"                                             ",
		"                                             ",
		"                                             ",
		"                                    o        ",
		"                                             ",
		"       @             o o                     ",
		"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"                                             ",
		"                                             "
	],
	[
		"                                             ",
		"                           o                 ",
		"                                             ",
		"                                             ",
		"           xx   xx      xx   xx              ",
		"  @        xx o xx      xx!!!xx       o o    ",
		"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"                                             ",
		"                                             "
	],
	[
		"                                          x  ",
		"                                          x  ",
		"                                     o    x  ",
		"                                    xxx   x  ",
		"   xx                                     x  ",
		"   x                         o            x  ",
		"   x                        xxx           x  ",
		"   x                 o                    x  ",
		"   x  @             xxx                   x  ",
		"   xxxxxxxxxxx                            x  ",
		"             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
		"             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
		"                                             ",
		"                                             "
	],
	[
		"                                             ",
		"                                             ",
		"  xx                                         ",
		"  x                                          ",
		"  x                 o     o     o     o      ",
		"  x                                          ",
		"  x  @                                       ",
		"  xxxxxxxxxxx    o     o     o     o     o   ",
		"            x   xxx   xxx   xxx   xxx   xxx  ",
		"            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
		"            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
		"            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"                                             ",
		"                                             "
	],
	[
		"      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"         |               xxxxxxxxxxxxxxxxxxxx",
		"             |                     xxxxxxxxxx",
		"                 |               |           ",
		"                     |       |       |       ",
		"  @    o   o   o   o   o | o   o   o   o | o ",
		"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"                                             ",
		"                                             "
	],
	[
		"                    xxx     xxx     xxx      ",
		"                   xx!xx   xx!xx   xx!xx     ",
		"                   x!!!x   x!!!x   x!!!x     ",
		"                   xx!xx   xx!xx   xx!xx     ",
		"                    xvx     xvx     xvx      ",
		"                                             ",
		"                                             ",
		"                                             ",
		"                                     o       ",
		"                                    xxx      ",
		"                             o               ",
		"                            xxx              ",
		"                                             ",
		"                     o                       ",
		"                    xxx                      ",
		"                                             ",
		"                                             ",
		"  @                                          ",
		"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
		"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	],
	[
		"                                                                                ",
		"                                                                                ",
		"                                                                                ",
		"                                                                                ",
		"                                                                                ",
		"                                                                                ",
		"                                                                  xxx           ",
		"                                                   xx      xx    xx!xx          ",
		"                                    o o      xx                  x!!!x          ",
		"                                                                 xx!xx          ",
		"                                   xxxxx                          xvx           ",
		"                                                                            xx  ",
		"  xx                                      o o                                x  ",
		"  x                     o                                                    x  ",
		"  x                                      xxxxx                             o x  ",
		"  x          xxxx       o                                                    x  ",
		"  x  @       x  x                                                xxxxx       x  ",
		"  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
		"                              x   x                  x     x                    ",
		"                              x!!!x                  x!!!!!x                    ",
		"                              x!!!x                  x!!!!!x                    ",
		"                              xxxxx                  xxxxxxx                    ",
		"                                                                                ",
		"                                                                                "
	],
	[
		"                                                                                             ",
		"                                                                                             ",
		"                       xxxx                                  =                             = ",
		"                       x  x                             =                             =      ",
		"                       x  x                        =                             =           ",
		"                       x  x                   =                             =                ",
		" @                   xxx  x              =                             =                 ooo ",
		"xxx                    x  x         =                             =                          ",
		"  x                    x  x    =                             =                           ooo ",
		"xxx         xxxx       x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"            x  x     o x                                                                     ",
		" oo         x  xxxxxxxxx                                                                     ",
		"xxxx       xx                                                                                ",
		"xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
		"xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	],
	[
		"          x                                           ",
		"          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"            !   o   !   o   !   o   !   o   !   o   ! ",
		"                                                      ",
		"                                                      ",
		"  @         o   !   o   !   o   !   o   !   o   !   o ",
		"xxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"xxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"xxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"xxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"          |                           |               ",
		"                                                  oo  ",
		"              |                  |         |          ",
		"                                                  oo  ",
		"                  |         |                   |     ",
		"                                                  oo  ",
		"                       |                              ",
		"!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	],
	[
		"                                                                   x  ",
		"                                                                   x  ",
		"                                                                   x  ",
		"                                                                   x  ",
		"                                                                   x  ",
		"        xxxxxx                                     ooo             x  ",
		"        x    x                        xxxx       xxxxxxxxx         x  ",
		"        x xx x                        x  x               x=        x  ",
		"        x x  x                        x  x               x=       ox  ",
		"        x xxxx                 xxxx   x  x               x        xx  ",
		"        x                      x  x   x  x               x       = x  ",
		"        x                      x  x   x  x               x       = x  ",
		"        x               xxxx   x  x   x  x               xo        x  ",
		"        x  @            x  x!!!x  x!!!x  x!!!!!!         xx        x  ",
		"        xxxxxxxxxxxxxxxxx  xxxxx  xxxxx  xxxxxx!         x         x  ",
		"                                               !         x =       x  ",
		"                                               !         x =      ox  ",
		"                                               !         x        xx  ",
		"                                               !         x   ooo   x  ",
		"                                               !         xxxxxxxxxxx  ",
		"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
		"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	],
	[
		"     x x    x x x    x x x    x x x    x x  ",
		"     x xxxxxx x xxxxxx x xxxxxx x xxxxxx x  ",
		"     x        x        x        x        x  ",
		"     x        x        x        x        x  ",
		"     |                 |                 |  ",
		"                                            ",
		"                                            ",
		"                                            ",
		"                                            ",
		"                                            ",
		"                                            ",
		"                                         o  ",
		"                                            ",
		"                                            ",
		"                                            ",
		"    @         |                 |           ",
		"   xxx        x        x        x        x  ",
		"!!!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
		"xxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"                                            "
	],
	[
		"                                      x!!x                        xxxxxxx                                    x!x  ",
		"                                      x!!x                     xxxx     xxxx                                 x!x  ",
		"                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
		"                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
		"                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
		"                                                xx!x         x     o   o                                    xx!x  ",
		"                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
		"                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
		"                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
		"                                                              xx!!!!!!!!!!!xx            v                        ",
		"                                                               xxxx!!!!!xxxx                                      ",
		"                                               x     x            xxxxxxx        xxx         xxx                  ",
		"                                               x     x                           x x         x x                  ",
		"                                               x     x                             x         x                    ",
		"                                               x     x                             xx        x                    ",
		"                                               xx    x                             x         x                    ",
		"                                               x     x      o  o     x   x         x         x                    ",
		"               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
		"              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
		"             xx       xx        x o x          x    xx               x   x   x               x                    ",
		"     @       x         x        x   x          x     x               x   x   x               x                    ",
		"    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
		"    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
		"!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
		"!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
		"!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
		"!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
		"!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
		"!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
		"!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "
	],
	[
		"                                                                                                              ",
		"                                                                                                              ",
		"                                                                                                              ",
		"                                                                                                              ",
		"                                                                                                              ",
		"                                        o                                                                     ",
		"                                                                                                              ",
		"                                        x                                                                     ",
		"                                        x                                                                     ",
		"                                        x                                                                     ",
		"                                        x                                                                     ",
		"                                       xxx                                                                    ",
		"                                       x x                 !!!        !!!  xxx                                ",
		"                                       x x                 !x!        !x!                                     ",
		"                                     xxx xxx                x          x                                      ",
		"                                      x   x                 x   oooo   x       xxx                            ",
		"                                      x   x                 x          x      x!!!x                           ",
		"                                      x   x                 xxxxxxxxxxxx       xxx                            ",
		"                                     xx   xx      x   x      x                                                ",
		"                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
		"                                      x   x           x                    x!!!x                              ",
		"                                      x   x           x                     xxx                               ",
		"                                     xx   xx          x                                                       ",
		"                                      x   x= = = =    x            xxx                                        ",
		"                                      x   x           x           x!!!x                                       ",
		"                                      x   x    = = = =x     o      xxx       xxx                              ",
		"                                     xx   xx          x                     x!!!x                             ",
		"                              o   o   x   x           x     x                xxv        xxx                   ",
		"                                      x   x           x              x                 x!!!x                  ",
		"                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
		"                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
		"                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
		"                             xx           xx                                         xxx                      ",
		"  xxx                         x     x     x                                         x!!!x                xxx  ",
		"  x x                         x    xxx    x                                          xxx                 x x  ",
		"  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
		"  x                           x           x                              x   x                             x  ",
		"  x                           xx          x                              x x x                             x  ",
		"  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
		"  x                xxx             o o    x                              x         xxx                     x  ",
		"  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
		"  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
		"  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
		"  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
		"  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
		"                                                                                                              ",
		"                                                                                                              "
	],
	[
		"                                                                                                  xxx x       ",
		"                                                                                                      x       ",
		"                                                                                                  xxxxx       ",
		"                                                                                                  x           ",
		"                                                                                                  x xxx       ",
		"                          o                                                                       x x x       ",
		"                                                                                             o o oxxx x       ",
		"                   xxx                                                                                x       ",
		"       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
		"       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
		"       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
		"       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
		"       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
		"                                                                                                              ",
		"          o              xxx                              xx                                                  ",
		"                                                                                                              ",
		"                                                                                                              ",
		"                                                      xx                                                      ",
		"                   xxx         xxx                                                                            ",
		"                                                                                                              ",
		"                          o                                                     x      x                      ",
		"                                                          xx     xx                                           ",
		"             xxx         xxx         xxx                                 x                  x                 ",
		"                                                                                                              ",
		"                                                                 ||                                           ",
		"  xxxxxxxxxxx                                                                                                 ",
		"  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
		"  x         x   x       x   x       x   x                 ||                  x     x                         ",
		"  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
		"  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
		"        x=                  =                =x   x                     xxx                                   ",
		"        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
		"                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"                                                                                                              "
	],
	[
		"                                            ",
		"o                                           ",
		"x x x x                                   o ",
		"                                  x   x   x ",
		"                                            ",
		"          x           x                     ",
		"                              x             ",
		"                                            ",
		"              x                             ",
		"                                  x         ",
		"                                            ",
		"                                            ",
		"                                      x     ",
		"                                            ",
		"                                            ",
		"                                          x ",
		"                                            ",
		"                 x                          ",
		"         x                            x     ",
		" x                                          ",
		"                        x                   ",
		"                                            ",
		"                                  x         ",
		"x                                           ",
		"                                            ",
		"                                            ",
		"       x        x        x                  ",
		"                                            ",
		"                                            ",
		"                               x            ",
		"                                        x   ",
		"                                            ",
		"                                            ",
		"                                            ",
		"                     x               x      ",
		"                                            ",
		"      x        x             x              ",
		" @                                          ",
		" x                                          ",
		"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
		"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	],
	[
		"                                                                    ",
		"o            oo           oo                 o         o         o  ",
		"             xx           xx                xxx       xxx       xxx ",
		"                                                                    ",
		"                                                  o         o       ",
		"                    o                            xxx       xxx      ",
		"             oo    xxx    oo   o o o o o o   o         o         o  ",
		"xx           xx           xx                xxx       xxx       xxx ",
		"    @                         o o o o o o o                         ",
		"xxxxxx!!!xxxxxxxxxxxxxxxxxxxx!x!x!x!x!x!x!x!x!x!!!!!!!!!!!!!!!!!!!!!",
		"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"                                                                    ",
		"                                                                    ",
		"                                                                    ",
		"                    o                         xx!!!!!!!!!!!!!!!!!!!!",
		"                                          xx  xx!!!!!!!!!!!!!!!!!!!!",
		"                                      xx  xx  xx!!!!!!!!!!!!!!!!!!!!",
		"                                  xx  xx  xx  xx!!!!!!!!!!!!!!!!!!!!",
		"                              xx  xx  xx  xx  xx!!!!!!!!!!!!!!!!!!!!",
		"                          xx!!xxo xx!!xxo xxooxx!!!!!!!!!!!!!!!!!!!!",
		"    @             ooooo   xxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!",
		"!!xxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	],
	[
		" xx=      x x=      x|x=      x x=      x|x ",
		"@x ooooooo   ooooooo   ooooooo   ooooooo    ",
		" x ooooooo   ooooooo   ooooooo   ooooooo    ",
		" x ooooooo   ooooooo   ooooooo   ooooooo    ",
		" x ooooooo | ooooooo   ooooooo | ooooooo    ",
		" xx      =x x      =x x      =x x      =x x ",
		" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
		"                                            ",
		"                                            ",
		"x                                          x",
		"x x  x   x   x   x   xx   x   x   x   x  x x",
		"x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x x",
		"x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx x",
		"xoxooooooooooox              xoooooooooooxox",
		"xoxooooooooooox              xoooooooooooxox",
		"xoxooooooooooox   xxx  xxx   xoooooooooooxox",
		"xoxxxxx   xxxxx   xoooooox   xxxxx   xxxxxox",
		"x                 xoooooox                 x",
		"x                 xoooooox                 x",
		"x xxxxx   xxxxx   xxxxxxxx   xxxxx   xxxxx x",
		"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
		"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	],
	[
		"                                            ",
		"                                            ",
		"                                            ",
		"  x  xx  xx  xx  xx  xx  xx  xx  xx  xx  x  ",
		"  x                                      x  ",
		"                                            ",
		"    oooooooooo oo         oo oooooooo       ",
		"  x oooooooooo ooo        oo ooooooooo   x  ",
		"  x oo         oooo       oo oo      oo  x  ",
		"    oo         oo oo      oo oo       oo    ",
		"    oo         oo  oo     oo oo       oo    ",
		"  x oooooooooo oo   oo    oo oo       oo x  ",
		"  x oooooooooo oo    oo   oo oo       oo x  ",
		"    oo         oo     oo  oo oo       oo    ",
		"    oo         oo      oo oo oo       oo    ",
		"  x oo         oo       oooo oo      oo  x  ",
		"  x oooooooooo oo        ooo ooooooooo   x  ",
		"    oooooooooo oo         oo oooooooo       ",
		"                                            ",
		"  x  @                                   x  ",
		"  x  xx  xx  xx  xx  xx  xx  xx  xx  xx  x  ",
		"                                            ",
		"                                            ",
		"                                            "
	]
];
